---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
                -5000:5000
        image: danielasanchez/iss_tracker #using dockerhub username
        #volumes:
        #   - ./config.yaml:/config.yaml #dash makes it a list (list of volumes)
